### PR TITLE
Switch txns to return instead of unnecessarily aborting in SEATS

### LINKED ISSUE #125: aborted transactions in SEATS
There are a number of instances in SEATS where a `UserAbortException` is thrown when it appears simply escaping the method would do.  This is particularly prevalent in `UpdateReservation`, `DeleteReservation` and `UpdateCustomer`.  This issue is to track the PR that will attempt to reduce the frequency of Aborted Transactions in the SEATS benchmark.

### PR DESCRIPTION
**Pull request by timveil**
this PR resolves #125

### CODE REVIEW

File: src/main/java/com/oltpbenchmark/benchmarks/seats/util/ErrorType.java [hunk 1]
```diff
@@ -35,7 +33,6 @@
     UNKNOWN;
 
     private final String errorCode;
-    private final static Pattern p = Pattern.compile("^(USER ABORT:[\\s]+)?E([\\d]{4})");
```
Comment (apavlo) [inline src/main/java/com/oltpbenchmark/benchmarks/seats/util/ErrorType.java:38]: I don't remember what I was using this for?

**Review by apavlo — APPROVED** [review]
LGTM
